services:
    metamodels.attribute_translatedfile.factory:
        class: MetaModels\AttributeTranslatedFileBundle\Attribute\AttributeTypeFactory
        arguments:
            - "@database_connection"
        tags:
            - { name: metamodels.attribute_factory }

    metamodels.attribute_translatedfile_order.factory:
        class: MetaModels\AttributeTranslatedFileBundle\Attribute\AttributeOrderTypeFactory
        arguments:
            - "@database_connection"
        tags:
            - { name: metamodels.attribute_factory }

    metamodels.attribute_translatedfile.event_listener_factory.add_attribute_information:
        class: MetaModels\AttributeTranslatedFileBundle\EventListener\AddAttributeInformation
        tags:
            -   name: kernel.event_listener
                event: metamodels.metamodel.collect-metamodel-attribute-information
                method: addInformation
                priority: -1

    metamodels.attribute_translatedfile.event_listener.image_size_options:
        class: MetaModels\AttributeTranslatedFileBundle\EventListener\ImageSizeOptions
        tags:
            -   name: kernel.event_listener
                event: dc-general.view.contao2backend.get-property-options
                method: getPropertyOptions

    metamodels.attribute_translatedfile.event_listener.remove_type_options:
        class: MetaModels\AttributeTranslatedFileBundle\EventListener\DcGeneral\Table\Attribute\RemoveTypeOptions
        tags:
            -   name: kernel.event_listener
                event: dc-general.view.contao2backend.get-property-options
                method: removeOption
                priority: -1

    metamodels.attribute_translatedfile.event_listener.remove_att_id_options:
        class: MetaModels\AttributeTranslatedFileBundle\EventListener\DcGeneral\Table\FilterSetting\RemoveAttIdOptions
        tags:
            -   name: kernel.event_listener
                event: dc-general.view.contao2backend.get-property-options
                method: removeOption
                priority: -1
