services:
  metamodels.attribute_translatedfile.factory:
    class: MetaModels\AttributeTranslatedFileBundle\Attribute\AttributeTypeFactory
    arguments:
      - "@database_connection"
    tags:
      - { name: metamodels.attribute_factory }
