services:
  metamodels.attribute_translatedfile.factory:
    class: MetaModels\AttributeTranslatedFileBundle\Attribute\AttributeTypeFactory
    arguments:
      - "@database_connection"
    tags:
      - { name: metamodels.attribute_factory }

  MetaModels\AttributeTranslatedFileBundle\EventListener\ImageSizeOptions:
    tags:
    -   name: kernel.event_listener
        event: dc-general.view.contao2backend.get-property-options
        method: getPropertyOptions
